# Generated by Django 6.0 on 2025-12-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Ссылка (например /category/notebooks)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('banner_type', models.CharField(choices=[('main', 'Главный (Большой)'), ('small', 'Маленький (Боковой)')], default='main', max_length=10)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
