# Generated by Django 6.0 on 2025-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-имя (например, about)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('content', models.TextField(verbose_name='Текст страницы (можно HTML)')),
                ('seo_title', models.CharField(blank=True, max_length=250, verbose_name='SEO Title (для браузера)')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO Description')),
            ],
            options={
                'verbose_name': 'Инфо-страница',
                'verbose_name_plural': 'Инфо-страницы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='SEO Title'),
        ),
    ]
