# Generated by Django 6.0 on 2025-12-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_infopage_product_seo_description_product_seo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+375 29 123 45 67', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(default='info@lana.by', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='г. Минск, пр. Независимости 100', max_length=200, verbose_name='Адрес')),
                ('telegram', models.URLField(blank=True, verbose_name='Ссылка на Telegram')),
                ('vk', models.URLField(blank=True, verbose_name='Ссылка на VK')),
                ('instagram', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
                ('odnoklassniki', models.URLField(blank=True, verbose_name='Ссылка на Одноклассники')),
                ('facebook', models.URLField(blank=True, verbose_name='Ссылка на Facebook')),
                ('tiktok', models.URLField(blank=True, verbose_name='Ссылка на TikTok')),
                ('youtube', models.URLField(blank=True, verbose_name='Ссылка на YouTube')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
