# Generated by Django 6.0 on 2025-12-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_size_product_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('main', 'Главный (Большой)'), ('small_top', 'Маленький (Боковой верхний)'), ('small_bottom', 'Маленький (Боковой нижний)')], default='main', max_length=20),
        ),
    ]
