# Generated by Django 6.0 on 2025-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_shippingmethod_alter_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (BYN)'),
        ),
    ]
