# Generated by Django 6.0 on 2025-12-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_shippingmethod_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('yookassa', 'ЮKassa (Карты РФ, SberPay)'), ('paritet', 'Паритет Банк (Карты РБ: Visa, MasterCard, BelKart)')], default='yookassa', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
